## Text Representation

In [2]:
# 1) Bag of words
# we use countvectorization

In [1]:
import numpy as np
import pandas as pd

In [5]:
df  = pd.DataFrame({'text':['people watch cricket','player was aplayer','people write comment',
                           'cricket play comment'],'output':[1,1,0,0]})

In [6]:
df

text  output
0  people watch cricket       1
1    player was aplayer       1
2  people write comment       0
3  cricket play comment       0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer()

In [12]:
bow = cv.fit_transform(df['text'])

In [13]:
# vocab
print(cv.vocabulary_)

{'people': 3, 'watch': 7, 'cricket': 2, 'player': 5, 'was': 6, 'aplayer': 0, 'write': 8, 'comment': 1, 'play': 4}


In [14]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 1 0 0 0 1 0]]
[[1 0 0 0 0 1 1 0 0]]


In [15]:
cv.transform(["Cricket watch and write comment of cricket comment"]).toarray()

array([[0, 2, 2, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [16]:
# 2) N-gram

In [17]:
# cv = CountVectorizer(ngram_range(2,2))

In [18]:
v = CountVectorizer(ngram_range=(1,2))

In [19]:
bow = v.fit_transform(df['text'])

In [20]:
df['text']

0    people watch cricket
1      player was aplayer
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [22]:
# vocab
print(v.vocabulary_)

{'people': 4, 'watch': 13, 'cricket': 2, 'people watch': 5, 'watch cricket': 14, 'player': 9, 'was': 11, 'aplayer': 0, 'player was': 10, 'was aplayer': 12, 'write': 15, 'comment': 1, 'people write': 6, 'write comment': 16, 'play': 7, 'cricket play': 3, 'play comment': 8}


In [23]:
# TF(Term Frequency)
# 2) IDF (Inverse Document Frequency)

In [24]:
# TF(t,d) = (Number of occurences of term t in document d)/(Total no of terms in document d)

# Example ==>
# d1=people watch cricket

# tf(people,d1) = 1/3

# d2= match was match
# tf(match,d2)=2/3

In [25]:
# IDF(t) = Loge(Total no of document in corpus)/(Number of documents with term t in them)
# here the corpus means no of sentecces

# Example ==>
# d1=people watch  cricket
# d2=cricket was cricket
# d3=people write comment
# d4=cricket with comment

# idf(cricket) = log(4/4)
# idf(people)=log(4/2)

In [26]:
# we cab use this by apply feature_extraction method in sklearn

In [27]:
df

text  output
0  people watch cricket       1
1    player was aplayer       1
2  people write comment       0
3  cricket play comment       0

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.52640543, 0.52640543, 0.        ,
        0.        , 0.        , 0.66767854, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.57735027, 0.        , 0.        ],
       [0.        , 0.52640543, 0.        , 0.52640543, 0.        ,
        0.        , 0.        , 0.        , 0.66767854],
       [0.        , 0.52640543, 0.52640543, 0.        , 0.66767854,
        0.        , 0.        , 0.        , 0.        ]])

In [30]:
print(tfidf.idf_)

[1.91629073 1.51082562 1.51082562 1.51082562 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073]


In [31]:
print(tfidf.get_feature_names_out())

['aplayer' 'comment' 'cricket' 'people' 'play' 'player' 'was' 'watch'
 'write']


## Word Embedding

In [ ]:
## In natural language processing 